BCDHX/Controllers/PaymentResultController.cs
using BCDHX.Models;
using BCDHX.Models.ModelObject;
using BCDHX.Moduns.Models;
using BCDHX.Moduns.Unity;
using BCDHX.Unity.PaymentBK;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace BCDHX.Controllers
{
    [Authorize(Roles ="Customer")]
    public class PaymentResultController : Controller
    {
        private const string CartSession = "CartSession";
        private readonly WebDieuHienDB _dbBCDH;
        private ApplicationUserManager _userManager;
        private readonly PaymentLibrary _paymentLibrary;
        public PaymentResultController()
        {
            _dbBCDH = new WebDieuHienDB();
            _paymentLibrary = new PaymentLibrary();
        }
        public PaymentResultController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;

        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: PaymentResult
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult WebHookResult(HttpContext context)
        {
            var jsonSerialzer = new JavaScriptSerializer();
            var jsonString = string.Empty;
            context.Request.InputStream.Position = 0;
            using (var inputStream = new StreamReader(context.Request.InputStream))
            {
                jsonString = inputStream.ReadToEnd();
            }
            var data = new PaymentWebWook();
            data = jsonSerialzer.Deserialize<PaymentWebWook>(jsonString);
            var number_ramdom = new RandomCode().RandomNumber(2);
            LinkSystem mg = new LinkSystem {ID_LinkSystem= Convert.ToInt32(number_ramdom)};
            _dbBCDH.Entry(mg).State = System.Data.Entity.EntityState.Added;
            _dbBCDH.SaveChanges();
            return new EmptyResult();
        }
        public ActionResult ShowTest()
        {
            

            return View();
        }
        public ActionResult Success()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ShowTest(string order)
        {
            
            var vnpayData = Request.QueryString;
            foreach (var item in vnpayData)
            {
                if (item!=null)
                {
                    ViewBag.TEST = item;
                }
                
            }
            ViewBag.X = order;

            return View();
        }
        public ActionResult ResultUseBalance(string id)
        {
            if (id!=null)
            {
                if (GetInvoieDetail(id).Count()==0 || GetInvoie(id)==null)
                {
                    return RedirectToAction("Index", "NotificationSystem");
                }else
                {
                    ViewBag.tempInvoieDetail = GetInvoieDetail(id);
                    ViewBag.tempInvoie = GetInvoie(id);
                    return View();

                }
            }else
            {
                return RedirectToAction("Index", "NotificationSystem");
            }

        }
       
       
        #region
        private InvoiceModel GetInvoie(string InvoiceID)
        {

            if (InvoiceID != null)
            {
                //var temp = _dbBCDH.InvoiceDetails.Select(x=>new InvoiceModelView {ID_Invoice = x.ID_Invoice,ID_InvoiceDetail=x.ID_InvoiceDetail,ID_Product=x.ID_Product,_Price=x.Price.Value,_Sale=x.Sale.Value,_ShippingFee=x.ShippingFee.Value,_StatusInvoice=x.StatusInvoice.Value,Quantity=x.Quantity.Value,ProcessOrder=x.ProcessOrder }).Where(x => x.ID_Invoice == InvoiceID).ToList();
                var temp = _dbBCDH.Invoices.Join(_dbBCDH.Accounts, invoice => invoice.ID_Account, account => account.ID_Account, (invoice, account) => new {Invoice=invoice,Account=account}).Select(x => new InvoiceModel { ID_Invoice = x.Invoice.ID_Invoice, Email=x.Invoice.Email,ID_Account=x.Account.ID_Account,Fullname=x.Account.Fullname,MaVanDon=x.Invoice.MaVanDon,Note=x.Invoice.Note,Orginal=x.Invoice.Orgin,Payment_Methods=x.Invoice.Payment_Methods,Phone=x.Invoice.Phone,PostCode=x.Invoice.PostCode,ProcessOrder=x.Invoice.ProcessOrder,Purchase_Date=x.Invoice.Purchase_Date,Shipping_Address=x.Invoice.Shipping_Address,Status_Order=x.Invoice.Status_Order}).Where(x => x.ID_Invoice == InvoiceID).SingleOrDefault();
                if (temp!=null)
                {
                    return temp;
                }
                else
                {
                    return temp = new InvoiceModel();
                }
            }
            else
            {
                return new InvoiceModel();
            }
        }
        private List<InvoiceModelView> GetInvoieDetail(string InvoiceID)
        {

            if (InvoiceID != null)
            {
                //var temp = _dbBCDH.InvoiceDetails.Select(x=>new InvoiceModelView {ID_Invoice = x.ID_Invoice,ID_InvoiceDetail=x.ID_InvoiceDetail,ID_Product=x.ID_Product,_Price=x.Price.Value,_Sale=x.Sale.Value,_ShippingFee=x.ShippingFee.Value,_StatusInvoice=x.StatusInvoice.Value,Quantity=x.Quantity.Value,ProcessOrder=x.ProcessOrder }).Where(x => x.ID_Invoice == InvoiceID).ToList();
                var temp = _dbBCDH.InvoiceDetails.Join(_dbBCDH.Products, invoiceDetail => invoiceDetail.ID_Product, product => product.ID_Product, (invoiceDetail, product) => new { InvoiceDetail = invoiceDetail, Product = product }).Select(x => new InvoiceModelView { ID_Invoice = x.InvoiceDetail.ID_Invoice, ID_InvoiceDetail = x.InvoiceDetail.ID_InvoiceDetail, ID_Product = x.InvoiceDetail.ID_Product, _Price = x.InvoiceDetail.Price.Value,  _ShippingFee = x.InvoiceDetail.ShippingFee.Value, _StatusInvoice = x.InvoiceDetail.StatusInvoice.Value, Quantity = x.InvoiceDetail.Quantity.Value, ProcessOrder = x.InvoiceDetail.ProcessOrder, NameProduct = x.Product.Name_Product }).Where(x => x.ID_Invoice == InvoiceID).ToList();
                if (temp.Count > 0)
                {
                    return temp;
                }
                else
                {
                    return temp = new List<InvoiceModelView>();
                }
            }
            else
            {
                return new List<InvoiceModelView>();
            }
        }
        public PartialViewResult PageBannerPaymentresult()
        {

            Silder tempImagePageBanner = _dbBCDH.Silders.Where(x => x.Title == "PageBannerForResult").SingleOrDefault() ?? new Silder();
            return PartialView(tempImagePageBanner);
        }
        #endregion
    }
}

BCDHX/Controllers/ProductController.cs
using BCDHX.Moduns.Models;
using System.Linq;
using System.Web.Mvc;
using BCDHX.Models.ModelObject;
using System.Collections.Generic;
using System;
using PagedList;
namespace BCDHX.Controllers
{
    public class ProductController : Controller
    {
        private WebDieuHienDB _dbBCDHX;

        public ProductController()
        {
            _dbBCDHX = new WebDieuHienDB();

        }


        public ActionResult Index(int? page, int? pagesize, string sortby, string selectmode)
        {
            string sortBy = (sortby ?? "def");
            string selectMode = (selectmode ?? "grid");
            int pageNumber = (page ?? 1);
            int pageSizeNumber = (pagesize ?? 8);
            var products = (from p in _dbBCDHX.Products
                            join g in _dbBCDHX.Categories on p.ID_Category equals g.ID_Category
                            join e in _dbBCDHX.ImageForProducts on p.ID_Product equals e.ID_Product
                            where p.Quantity > 0
                            orderby p.Name_Product
                            select new Models.ModelObject.Product
                            {
                                ID_Product = p.ID_Product,
                                ID_Category = p.ID_Category,
                                Name_Product = p.Name_Product,
                                Quantity = p.Quantity.Value,
                                Price = p.Price.Value.ToString(),
                                Status = p.Status.Value,
                                Sale = p.Sale.Value.ToString(),
                                Img = e.IMG1,
                                Description = p.Description,
                                NameCatogory = g.Name_Category
                            }
                         ).ToList();
            ViewBag.tempSortBy = sortby;
            ViewBag.Temppagesize = pageSizeNumber;
            ViewBag.SelectMode = selectMode;
            switch (sortby)
            {
                case "trending":
                    products = products.Select(x => x).OrderBy(x => x.Name_Product).Where(x => x.Status == 3 || x.Status == 2).ToList();
                    break;
                case "sales":
                    products = products.Select(x => x).OrderBy(x => x.Name_Product).Where(x => x.Status == 3).ToList();
                    break;
                case "bestdeal":
                    products = products.Select(x => x).OrderBy(x => x.Name_Product).Where(x => x.Status == 4).ToList();
                    break;
                case "date":
                    products = products.Select(x => x).OrderBy(x => x.Name_Product).Where(x => x.Status == 2).ToList();
                    break;
                case "priceasc":
                    products = (from p in _dbBCDHX.Products
                                join e in _dbBCDHX.ImageForProducts
                                on p.ID_Product equals e.ID_Product
                                where p.Quantity > 0
                                orderby p.Price
                                select new Models.ModelObject.Product
                                {
                                    ID_Product = p.ID_Product,
                                    ID_Category = p.ID_Category,
                                    Name_Product = p.Name_Product,
                                    Quantity = p.Quantity.Value,
                                    Price = p.Price.Value.ToString(),
                                    Status = p.Status.Value,
                                    Sale = p.Sale.Value.ToString(),
                                    Img = e.IMG1,
                                    Description = p.Description
                                }
                         ).ToList();
                    break;
                case "pricedesc":
                    products = (from p in _dbBCDHX.Products
                                join e in _dbBCDHX.ImageForProducts
                                on p.ID_Product equals e.ID_Product
                                where p.Quantity > 0
                                orderby p.Price descending
                                select new Models.ModelObject.Product
                                {
                                    ID_Product = p.ID_Product,
                                    ID_Category = p.ID_Category,
                                    Name_Product = p.Name_Product,
                                    Quantity = p.Quantity.Value,
                                    Price = p.Price.Value.ToString(),
                                    Status = p.Status.Value,
                                    Sale = p.Sale.Value.ToString(),
                                    Img = e.IMG1,
                                    Description = p.Description
                                }
                         ).ToList();
                    break;
                default:

                    break;
            }
            return View(products.ToPagedList(pageNumber, pageSizeNumber));
        }

        public ActionResult ProductByCategory(string categoryname, int? page, int? pagesize, string sortby, string selectmode)
        {
            string sortBy = (sortby ?? "def");
            string selectMode = (selectmode ?? "grid");
            int pageNumber = (page ?? 1);
            int pageSizeNumber = (pagesize ?? 8);
            var tempProductWithCategory = (from p in _dbBCDHX.Products
                                           join e in _dbBCDHX.ImageForProducts on p.ID_Product equals e.ID_Product
                                           join g in _dbBCDHX.Categories on p.ID_Category equals g.ID_Category
                                           where p.Quantity>0
                                           select new Models.ModelObject.Product
                                           {
                                               ID_Product = p.ID_Product,
                                               ID_Category = p.ID_Category,
                                               Name_Product = p.Name_Product,
                                               Quantity = p.Quantity.Value,
                                               Price = p.Price.Value.ToString(),
                                               Status = p.Status.Value,
                                               Sale = p.Sale.Value.ToString(),
                                               Img = e.IMG1,
                                               Description = p.Description,
                                               NameCatogory = g.Name_Category

                                           }).ToList().Where(x => x.NameCatogory == categoryname || x.ID_Category.StartsWith(categoryname));
            ViewBag.tempSortBy = sortby;
            ViewBag.Temppagesize = pageSizeNumber;
            ViewBag.SelectMode = selectMode;
            switch (sortby)
            {
                case "trending":
                    tempProductWithCategory = tempProductWithCategory.Select(x => x).OrderBy(x => x.Name_Product).Where(x => x.Status == 3 || x.Status == 2).ToList();
                    break;
                case "sales":
                    tempProductWithCategory = tempProductWithCategory.Select(x => x).OrderBy(x => x.Name_Product).Where(x => x.Status == 3).ToList();
                    break;
                case "bestdeal":
                    tempProductWithCategory = tempProductWithCategory.Select(x => x).OrderBy(x => x.Name_Product).Where(x => x.Status == 4).ToList();
                    break;
                case "date":
                    tempProductWithCategory = tempProductWithCategory.Select(x => x).OrderBy(x => x.Name_Product).Where(x => x.Status == 2).ToList();
                    break;
                case "priceasc":
                    tempProductWithCategory = (from p in _dbBCDHX.Products
                                               join e in _dbBCDHX.ImageForProducts on p.ID_Product equals e.ID_Product
                                               join g in _dbBCDHX.Categories on p.ID_Category equals g.ID_Category
                                               where p.Quantity > 0
                                               orderby p.Price
                                               select new Models.ModelObject.Product
                                               {
                                                   ID_Product = p.ID_Product,
                                                   ID_Category = p.ID_Category,
                                                   Name_Product = p.Name_Product,
                                                   Quantity = p.Quantity.Value,
                                                   Price = p.Price.Value.ToString(),
                                                   Status = p.Status.Value,
                                                   Sale = p.Sale.Value.ToString(),
                                                   Img = e.IMG1,
                                                   Description = p.Description
                                               } ).ToList();                       
                    break;
                    case "pricedesc":
                    tempProductWithCategory = (from p in _dbBCDHX.Products
                                               join e in _dbBCDHX.ImageForProducts on p.ID_Product equals e.ID_Product
                                               join g in _dbBCDHX.Categories on p.ID_Category equals g.ID_Category
                                               where p.Quantity > 0
                                               orderby p.Price descending
                                               select new Models.ModelObject.Product
                                               {
                                                   ID_Product = p.ID_Product,

BCDHX/Views/PaymentResult/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/HomeTempates/_LayoutOther.cshtml";
}

@section PageBannerForAll{
    @Html.Action("PageBannerPaymentresult", "PaymentResult")
}
<div class="invoice-box">
    <table cellpadding="0" cellspacing="0">
        <tr class="top">
            <td colspan="2">
                <table>
                    <tr>
                        <td class="title">
                            @*<img src="https://www.sparksuite.com/images/logo.png" style="width:100%; max-width:300px;">*@
                        </td>

                        <td>
                            Mã đơn hàng #: 123<br>
                            Ngày mua: January 1, 2015
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr class="information">
            <td colspan="2">
                <table>
                    <tr>
                        <td>
                            Sparksuite, Inc.<br>
                            12345 Sunny Road<br>
                            Sunnyville, CA 12345
                        </td>

                        <td>
                            Acme Corp.<br>
                            John Doe<br>
                            john@example.com
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr class="heading">
            <td>
                Payment Method
            </td>

            <td>
                Check #
            </td>
        </tr>

        <tr class="details">
            <td>
                Check
            </td>

            <td>
                1000
            </td>
        </tr>

        <tr class="heading">
            <td>
                Item
            </td>

            <td>
                Price
            </td>
        </tr>

        <tr class="item">
            <td>
                Website design
            </td>

            <td>
                $300.00
            </td>
        </tr>

        <tr class="item">
            <td>
                Hosting (3 months)
            </td>

            <td>
                $75.00
            </td>
        </tr>

        <tr class="item last">
            <td>
                Domain name (1 year)
            </td>

            <td>
                $10.00
            </td>
        </tr>

        <tr class="total">
            <td></td>

            <td>
                Total: $385.00
            </td>
        </tr>
    </table>
</div>
@section Brands{
    @Html.Partial("~/Views/Home/BrandsPartial.cshtml")
}
@section Subscribe{
    @Html.Partial("~/Views/Home/SubscribePartial.cshtml")
}
@section ScriptBundle {
    <script src="@Url.Content("~/ScriptsBundle/CheckOut/CheckOut.min.js")"></script>
}

BCDHX/Views/PaymentResult/PageBannerPaymentresult.cshtml
@model BCDHX.Moduns.Models.Silder
<div class="page-banner-section section">
    <div class="page-banner-wrap row row-0 d-flex align-items-center ">

        <!-- Page Banner -->
        <div class="col-lg-4 col-12 order-lg-2 d-flex align-items-center justify-content-center">
            <div class="page-banner">
                <h1>Thông tin đơn hàng</h1>
                <div class="breadcrumb">
                    <ul>
                        <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                        <li>@Html.ActionLink("Shop", "Index", "Product")</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Banner -->
        <div class="col-lg-4 col-md-6 col-12 order-lg-1">
            <div class="banner">
                <a href="#">
                    @if (Model.Img != null)
                    {
                        <img src="@Url.Content("~/Content/ImageUploaded/ImageBanner/"+Model.Img)" alt="Banner">
                    }
                    else
                    {
                        <img src="@Url.Content("~/Content/MainPage/images/banner/banner-15.jpg")" alt="Banner">
                    }
                </a>
            </div>
        </div>

        <!-- Banner -->
        <div class="col-lg-4 col-md-6 col-12 order-lg-3">
            <div class="banner">
                <a href="#">
                    @if (Model.Img != null)
                    {
                        <img src="@Url.Content("~/Content/ImageUploaded/ImageBanner/"+Model.Img)" alt="Banner">
                    }
                    else
                    {
                        <img src="@Url.Content("~/Content/MainPage/images/banner/banner-15.jpg")" alt="Banner">
                    }
                </a>
            </div>
        </div>
    </div>
</div>

BCDHX/Views/PaymentResult/ResultUseBalance.cshtml
@using BCDHX.Models
@using System.Globalization
@{
                /**/

                ViewBag.Title = "ResultUseBalance";
                Layout = "~/Views/Shared/HomeTempates/_LayoutOther.cshtml";
                var tempInvoices = (InvoiceModel)ViewBag.tempInvoie;
                var tempInvoiceDetail = (List<InvoiceModelView>)ViewBag.tempInvoieDetail;
                var shipping = new Decimal(0);
                foreach (var item in tempInvoiceDetail)
                {
                    shipping = item._ShippingFee;
                }
                var totalGrand = string.Format(CultureInfo.GetCultureInfo("vi-VN"), "{0:C}", tempInvoiceDetail.Sum(x => x._Price) + shipping);
}

@section PageBannerForAll{
    @Html.Action("PageBannerPaymentresult", "PaymentResult")
}
<div class="invoice-box">
    <table cellpadding="0" cellspacing="0">
        <tr class="top">
            <td colspan="2">
                <table>
                    <tr>
                        <td class="title">
                            @*<img src="https://www.sparksuite.com/images/logo.png" style="width:100%; max-width:300px;">*@
                        </td>
                        <td>
                            <strong>Mã đơn hàng #</strong>: @tempInvoices.ID_Invoice<br>
                            <strong>Ngày mua:</strong> @tempInvoices.Purchase_Date<br>
                            <strong>Tình trạng:</strong> @(tempInvoices.Status_Order.GetValueOrDefault(true))
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr class="information">
            <td colspan="2">
                <table>
                    <tr>
                        <td>
                            <strong>Địa chỉ:</strong> @tempInvoices.Shipping_Address
                        </td>

                        <td>
                            @tempInvoices.Fullname<br>
                            @tempInvoices.Email
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr class="heading">
            <td>
                Phương thức thanh toán
            </td>

            <td>
                Check #
            </td>
        </tr>

        <tr class="details">
            <td>
                @tempInvoices.Payment_Methods
            </td>
        </tr>

        <tr class="heading">
            <td>
                Danh sách sản phẩm
            </td>

            <td>
                Giá
            </td>
        </tr>
        @foreach (var item in tempInvoiceDetail)
        {
            <tr class="item">
                <td>
                    @item.NameProduct
                </td>

                <td>
                    @item.Price
                </td>
            </tr>
        }
        <tr class="total">
            <td></td>

            <td>
                Tổng tiền (Tổng sản phẩm + ship): @totalGrand
            </td>
        </tr>
    </table>
</div>
@section Brands{
    @Html.Partial("~/Views/Home/BrandsPartial.cshtml")
}
@section Subscribe{
    @Html.Partial("~/Views/Home/SubscribePartial.cshtml")
}

BCDHX/Views/PaymentResult/ShowTest.cshtml
@{
    ViewBag.Title = "WebHookBK";
    Layout = "~/Views/Shared/HomeTempates/_LayoutOther.cshtml";
}

<h2>@ViewBag.TEST</h2>
<h2>@ViewBag.X</h2>

BCDHX/Views/PaymentResult/WebHookResult.cshtml
@{
    ViewBag.Title = "WebHookResult";
    Layout = "~/Views/Shared/HomeTempates/_LayoutOther.cshtml";
}

<h2>WebHookResult</h2>