BCDHX/Controllers/WishListProductController.cs
using BCDHX.Models.ModelObject;
using BCDHX.Moduns.Models;
using BCDHX.Moduns.Unity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BCDHX.Controllers
{
    [Authorize(Roles = "Customer")]
    public class WishListProductController : Controller
    {
        private WebDieuHienDB _dbBCDHX;
        private ApplicationUserManager _userManager;
        private RandomCode _randomcode;
        public WishListProductController()
        {
            _dbBCDHX = new WebDieuHienDB();
            _randomcode = new RandomCode();

        }
        public WishListProductController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;

        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        [HttpPost]
        public async Task<JsonResult> AddWishList(string productID)
        {
            if (productID != null || productID != "")
            {
                var userTemp = await UserManager.FindByEmailAsync(User.Identity.Name);
                if (userTemp != null)
                {
                    var productExsit = _dbBCDHX.WishLists.AsNoTracking().Where(x => x.ID_Account == userTemp.Id && x.ID_Product == productID).SingleOrDefault();
                    if (productExsit != null)
                    {
                        return Json(new { Error = "Sản phẩm đã tồn tại trong wishList", Status = 3 });
                    }
                    else
                    {
                        var productTemp = _dbBCDHX.Products.AsNoTracking().Where(x => x.ID_Product == productID).SingleOrDefault();
                        if (productTemp != null)
                        {
                            var wishListID = _randomcode.RandomNumber(4);
                            WishList wishListmodel = new WishList { ID_Account = userTemp.Id, ID_Product = productID, ID_WishList = wishListID };
                            _dbBCDHX.Entry(wishListmodel).State = System.Data.Entity.EntityState.Added;
                            _dbBCDHX.SaveChanges();
                            return Json(new { Error = "Thêm sản phẩm thành công vào wishList", Status = 1 });
                        }
                        else
                        {
                            return Json(new { Error = "Lỗi sảy ra", Status = 2 });
                        }

                    }
                }
                else
                {
                    return Json(new { Error = "Bạn phải đăng nhập mới thêm sản phẩm vào wishList của mình được!", Status = 4 });
                }

            }
            else
            {
                return Json(new { Error = "Lỗi sảy ra", Status = 2 });
            }
        }
        public async Task<ActionResult> Index()
        {
            var userTemp = await UserManager.FindByEmailAsync(User.Identity.Name);
            var tempProductId = _dbBCDHX.WishLists.Where(x => x.ID_Account == userTemp.Id).Select(x => new { wishListId = x.ID_WishList, ID_Product = x.ID_Product });
            WishListViewModel tempWishListViewModel = new WishListViewModel();
            List<Models.ModelObject.Product> tempWishListProduct = new List<Models.ModelObject.Product>();
            tempWishListViewModel.ID_Account = userTemp.Id;
            foreach (var item in tempProductId)
            {
                var products = (from p in _dbBCDHX.Products
                                join g in _dbBCDHX.Categories on p.ID_Category equals g.ID_Category
                                join e in _dbBCDHX.ImageForProducts on p.ID_Product equals e.ID_Product
                                where p.Quantity > 0
                                orderby p.Name_Product
                                select new Models.ModelObject.Product
                                {
                                    ID_Product = p.ID_Product,
                                    ID_Category = p.ID_Category,
                                    Name_Product = p.Name_Product,
                                    Quantity = p.Quantity.Value,
                                    Price = p.Price.Value.ToString(),
                                    Status = p.Status.Value,
                                    Sale = p.Sale.Value.ToString(),
                                    Img = e.IMG1,
                                    Description = p.Description,
                                    NameCatogory = g.Name_Category
                                }
                         ).Where(x => x.ID_Product == item.ID_Product).SingleOrDefault();

                if (products != null)
                {
                    tempWishListViewModel.IdWishList = item.wishListId;
                    tempWishListProduct.Add(products);
                }
            }
            tempWishListViewModel.ListProductWishList = tempWishListProduct;
            return View(tempWishListViewModel);
        }
        [HttpPost]
        public async Task<JsonResult> RemoveWishListItem(string productId)
        {
            if (productId != null || productId != "")
            {
                var userTemp = await UserManager.FindByEmailAsync(User.Identity.Name);
                var tempWishList = _dbBCDHX.WishLists.AsNoTracking().Where(x => x.ID_Product == productId && x.ID_Account == userTemp.Id).SingleOrDefault();
                _dbBCDHX.Entry(tempWishList).State = System.Data.Entity.EntityState.Deleted;
                _dbBCDHX.SaveChanges();
                return Json(new { Error = "Xóa item thành công", Status = 0 });
            }
            else
            {
                return Json(new { Error = "Lỗi xảy ra", Status = 1 });
            }

        }
      
        public PartialViewResult PageBannerForWishList()
        {
            Silder tempImagePageBanner = _dbBCDHX.Silders.Where(x => x.Title == "PageBannerForWishList").SingleOrDefault() ?? new Silder();
            return PartialView(tempImagePageBanner);
        }
    }
}

BCDHX/Views/WishListProduct/Index.cshtml
@model BCDHX.Models.ModelObject.WishListViewModel
@{
    ViewBag.Title = "Danh sách mong ước";
    Layout = "~/Views/Shared/HomeTempates/_LayoutOther.cshtml";
}

@section PageBannerForAll
{
    @Html.Action("PageBannerForWishList", "WishListProduct")
}
<div class="row">
    <div class="col-12">
        <form action="#">
            <div class="cart-table table-responsive">
                @if (Model.ListProductWishList == null)
                {
                    <p>Danh sách ước mơ trống!</p>
                }
                else
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="pro-thumbnail">Ảnh</th>
                                <th class="pro-title">Tên sản phẩm</th>
                                <th class="pro-price">Giá</th>
                                <th class="pro-subtotal">Mua</th>
                                <th class="pro-remove">Xóa</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ListProductWishList)
                            {
                                <tr>
                                    <td class="pro-thumbnail"><a href="../Product/ProductDetail/?productid=@item.ID_Product"><img src="@Url.Content("~/Content/ImageUploaded/ImageForProduct/" + item.Img)" alt="Product"></a></td>
                                    <td class="pro-title"><a href="../Product/ProductDetail/?productid=@item.ID_Product">@item.Name_Product</a></td>
                                    <td class="pro-price">
                                        @if (!item.Sale.Equals("null"))
                                        {
                                            <h5 class="price"><span class="old">@item.Price</span>@item.Sale</h5>
                                        }
                                        else
                                        {
                                            <h5 class="price">@item.Price</h5>
                                        }
                                    </td>
                                    <td class="pro-addtocart"><button>Mua ngay</button></td>
                                    <td class="pro-remove"><a href="#" onclick="return removeWishList('@item.ID_Product')"><i class="fas fa-trash-alt"></i></a></td>
                                </tr>
                            }


                        </tbody>
                    </table>
                }

            </div>

        </form>

    </div>
</div>

@section Brands
{
    @Html.Partial("~/Views/Home/BrandsPartial.cshtml")
}
@section Subscribe{
    @Html.Partial("~/Views/Home/SubscribePartial.cshtml")
}
@section ScriptBundle
{

    <script src="@Url.Content("~/ScriptsBundle/WishList/WishList.min.js")"></script>
}

BCDHX/Views/WishListProduct/PageBannerForWishList.cshtml
@model BCDHX.Moduns.Models.Silder
<!-- Page Banner Section Start -->
<div class="page-banner-section section">
    <div class="page-banner-wrap row row-0 d-flex align-items-center ">

        <!-- Page Banner -->
        <div class="col-lg-4 col-12 order-lg-2 d-flex align-items-center justify-content-center">
            <div class="page-banner">
                <h1>D.sách mong ước</h1>
                <p>Ở đây sẽ có các sản phẩm được bạn lưu vào danh sách mong ước của mình, hoặc có thể yêu cầu give away qua các event của shop!</p>
                <div class="breadcrumb">
                    <ul>
                        <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                        <li>@Html.ActionLink("D.sách sản phẩm", "Index", "Product")</li>
                        <li>@Html.ActionLink("D.sách mong ước", "Index", "WishListProduct")</li>
                      
                    </ul>
                </div>
            </div>
        </div>

        <!-- Banner -->
        <div class="col-lg-4 col-md-6 col-12 order-lg-1">
            <div class="banner">
                <a href="#">
                    @if (Model.Img != null)
                    {
                        <img src="@Url.Content("~/Content/ImageUploaded/ImageBanner/"+Model.Img)" alt="Banner">
                    }
                    else
                    {
                        <img src="@Url.Content("~/Content/MainPage/images/banner/banner-15.jpg")" alt="Banner">
                    }
                </a>
            </div>
        </div>

        <!-- Banner -->
        <div class="col-lg-4 col-md-6 col-12 order-lg-3">
            <div class="banner">
                <a href="#">
                    @if (Model.Img != null)
                    {
                        <img src="@Url.Content("~/Content/ImageUploaded/ImageBanner/"+Model.Img)" alt="Banner">
                    }
                    else
                    {
                        <img src="@Url.Content("~/Content/MainPage/images/banner/banner-15.jpg")" alt="Banner">
                    }
                </a>
            </div>
        </div>

    </div>
</div><!-- Page Banner Section End -->