BCDHX/Areas/AdminBCDH/Controllers/ManagerController.cs
using BCDHX.Models;
using BCDHX.Moduns.Models;
using BCDHX.Moduns.Unity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BCDHX.Areas.AdminBCDH.Controllers
{
    [CustomeAuthorizeAdmin(Roles = "Admin,Staff,Manager")]
    public class ManagerController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        public WebDieuHienDB _db;
        private ApplicationDbContext _dbasp;
        public ManagerController()
        {
            _db = new WebDieuHienDB();
            _dbasp = new ApplicationDbContext();
        }
        public ManagerController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        
        public async Task<ActionResult> Index()
        {
            var tempUserOrginData = await UserManager.FindByEmailAsync(User.Identity.Name);
            var tempUser = _db.AdminUsers.Select(x=>new UserAdminModelAdmin {Access= x.Acess.Value.ToString(),Fullname=x.FullName,ID_AdminUser=x.ID_AdminUser,Img=x.Img,Password=x.Password,Username=x.UserName }).Where(x => x.ID_AdminUser==tempUserOrginData.Id).SingleOrDefault();
           
            return View(tempUser);
        }
        
        [HttpPost]
        public JsonResult ValidateOldPassword(string oldpassword)
        {
            var UserId = User.Identity.GetUserId();
            var rs = _db.AdminUsers.Where(x => x.Password == oldpassword && x.ID_AdminUser== UserId).SingleOrDefault();
            if (rs!=null)
            {
                return Json(new { Result = true });
            }
            return Json(new { Result = false });
        }
        [HttpPost]
        public async Task<JsonResult> UpdatePasswordPrivate(string NewPassword)
        {
            var UserTemp = UserManager.FindById(User.Identity.GetUserId());
            if (await ChangePassword(NewPassword,UserTemp.Id))
            {
                var UserTempAdminAccount = _db.AdminUsers.Where(x => x.ID_AdminUser == UserTemp.Id).SingleOrDefault();
                UserTempAdminAccount.Password = NewPassword;
                _db.Entry(UserTempAdminAccount).State = System.Data.Entity.EntityState.Modified;
                return _db.SaveChanges()>0? Json(new { Result=true}):Json(new { Result=false });
            }
            return Json(new { Result = false });


        }
        [HttpPost]
        public JsonResult UpdateFullnamePrivate(string Fullname)
        {
            if (Fullname!=null)
            {
                var UserTemp = UserManager.FindById(User.Identity.GetUserId());
                var UserTempAdminAccount = _db.AdminUsers.Where(x => x.ID_AdminUser == UserTemp.Id).SingleOrDefault();
                UserTempAdminAccount.FullName = Fullname;
                _db.Entry(UserTempAdminAccount).State = System.Data.Entity.EntityState.Modified;
                    return _db.SaveChanges() > 0 ? Json(new { Result = true }) : Json(new { Result = false });
            }
            return Json(new { Result = false });
        }

        private async Task<bool> ChangePassword(string key,string id)
        {
            var TempUserOrgin = _db.AdminUsers.AsNoTracking().SingleOrDefault(x => x.ID_AdminUser == key);
            
                IdentityResult resultValidate = await UserManager.PasswordValidator.ValidateAsync(key);
                if (resultValidate.Succeeded)
                {
                    var CodedRestPasswor = await UserManager.GeneratePasswordResetTokenAsync(id);
                    var result = await UserManager.ResetPasswordAsync(id, CodedRestPasswor, key);
                    return result.Succeeded;
                }
                else
                {
                    return false;
                }
        }
        #region
        [HttpGet]
        public JsonResult GetImageStaffAvatar()
        {
            var UserId = User.Identity.GetUserId();
            var TempAvatar = _db.AdminUsers.Where(x => x.ID_AdminUser == UserId).Select(x => x.Img).SingleOrDefault();
            return Json(new {IMG = TempAvatar},JsonRequestBehavior.AllowGet);
        }
#endregion

    }
}

BCDHX/Areas/AdminBCDH/Views/Manager/Index.cshtml
@model BCDHX.Models.UserAdminModelAdmin
@{
    ViewBag.Title = "Thông tin tài khoản";
    Layout = "~/Areas/AdminBCDH/Views/Shared/_LayoutAdmin.cshtml";
}

@section Breadcrums{
    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-4">
                    <div class="page-header float-left">
                        <div class="page-title">

                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="page-header float-right">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li>@Html.ActionLink("Thống kê", "Index", "Home")</li>
                                <li class="active">@Html.ActionLink("Thông tin tài khoản", "Index", "Manager")</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-lg">
        <div class="card">
            <div class="card-header">
                <h4>Thông tin tài khoản</h4>
            </div>
            <div class="card-body">
                <div class="custom-tab">
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="custom-nav-home-tab" data-toggle="tab" href="#custom-nav-home" role="tab" aria-controls="custom-nav-home" aria-selected="true">Thông tin tài khoản chung</a>
                            <a class="nav-item nav-link" id="custom-nav-profile-tab" data-toggle="tab" href="#custom-nav-profile" role="tab" aria-controls="custom-nav-profile" aria-selected="false">Đổi mật khẩu</a>
                            <a class="nav-item nav-link" id="custom-nav-contact-tab" data-toggle="tab" href="#custom-nav-contact" role="tab" aria-controls="custom-nav-contact" aria-selected="false">Contact</a>
                        </div>
                    </nav>
                    <div class="tab-content pl-3 pt-2" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="custom-nav-home" role="tabpanel" aria-labelledby="custom-nav-home-tab">
                            <div class="row">
                                <div class="col-sm-10"><h1>Xin chào,@Model.Fullname</h1></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3">
                                    <!--left col-->
                                    <div class="text-center">
                                        <img src="@Url.Content("~/Content/ImageUploaded/ImageForUser/"+Model.Img)" class="avatar img-circle img-thumbnail" alt="avatar">
                                        <h6>Sử dụng ảnh khác...</h6>
                                        <div id="UploadImageAvatarPrivatePresonZone"></div>
                                    </div><br>
                                   
                                </div><!--/col-3-->
                                <div class="col-sm-9">
                                    <ul class="nav nav-tabs">
                                        <li class="active"><a data-toggle="tab" href="#home">Home</a></li>                                     
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="home">
                                            <hr>
                                            <form class="form" id="UpdatePersonPrivate">
                                                <div class="form-group">
                                                    <div class="col-xs-6">
                                                        <label for="first_name"><h4>Mã staff:</h4></label>
                                                        <input type="text" class="form-control"    value="@Model.ID_AdminUser" readonly>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-xs-6">
                                                        <label for="first_name"><h4>Họ và tên:</h4></label>
                                                        <input type="text" class="form-control" name="first_name" id="Fullname" placeholder="Họ và tên" value="@Model.Fullname" required>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-xs-6">
                                                        <label for="phone"><h4>Tên tài khoản</h4></label>
                                                        <input type="text" class="form-control" value="@Model.Username" readonly>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-xs-6">
                                                        <label for="mobile"><h4>Quyền hạn</h4></label>
                                                        <input type="text" class="form-control" value="@Model.Access" readonly>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-xs-12">
                                                        <br>
                                                        <button class="btn btn-lg btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Thay đổi</button>
                                                        <button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button>
                                                    </div>
                                                </div>
                                            </form>

                                            <hr>

                                        </div>

                                    </div><!--/tab-pane-->
                                </div><!--/tab-content-->

                            </div><!--/col-9-->
                        </div>

                        <div class="tab-pane fade" id="custom-nav-profile" role="tabpanel" aria-labelledby="custom-nav-profile-tab">
                            <form  id="formUpdatePersonPrivatePassword">
                                <div id="UpdatePersonPrivatePassword">

                                </div>
                                </form>
                                @*<form class="form" id="UpdatePersonPrivatePassword">
                <div class="form-group">
                    <div class="col-xs-6">
                        <label for="first_name"><h4>Mật khẩu cũ:</h4></label>
                        <input type="text" class="form-control"  id="Fullname"   required>
                    </div>
                </div>
            </form>*@
                        </div>
                        <div class="tab-pane fade" id="custom-nav-contact" role="tabpanel" aria-labelledby="custom-nav-contact-tab">
                            <p>đang phát triển nốt</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /# column -->
@section scripts{
    <script src="@Url.Content("~/ScriptsBundle/AdminJquery/Manager/ManagerAccountPrivate.js")"></script>
}